ls ArduboyCollection/Action > gindex/action.txt
ls ArduboyCollection/Application > gindex/application.txt
ls ArduboyCollection/Arcade > gindex/arcade.txt
ls ArduboyCollection/Demo > gindex/demo.txt
ls ArduboyCollection/Misc > gindex/misc.txt
ls ArduboyCollection/Platformer > gindex/platformer.txt
ls ArduboyCollection/Puzzle > gindex/puzzle.txt
ls ArduboyCollection/Racing > gindex/racing.txt
ls ArduboyCollection/RPG > gindex/rpg.txt
ls ArduboyCollection/Shooter > gindex/shooter.txt
ls ArduboyCollection/Sports > gindex/sports.txt